title: "一般的な議論"
labels: [discussion]
body:
  - type: markdown
    attributes:
      value: |
        👋 ディスカッションフォーラムへようこそ！
        
        ここは以下のための場所です：
        - 学割サービスの使用に関する質問
        - コツや裏技の共有
        - 潜在的な改善点の議論
        - 他のユーザーとの交流
        
        敬意を持ち、コミュニティガイドラインに従ってください。

  - type: dropdown
    id: category
    attributes:
      label: 議論のカテゴリ
      description: どのような種類の議論ですか？
      options:
        - 一般的な質問
        - 使用法のコツ
        - アイデアと提案
        - ショーアンドテル
        - ヘルプ募集
        - その他
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: 議論内容
      description: 何を議論したいですか？
      placeholder: あなたの考え、質問、アイデアを共有してください...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: 追加情報
      description: 役に立つかもしれない追加情報
      placeholder: ブラウザバージョン、具体的な使用例、関連リンクなど