title: "❓ ヘルプとサポート"
labels: [discussion, help, support]
body:
  - type: markdown
    attributes:
      value: |
        ❓ **ヘルプが必要ですか？** 
        
        ここで質問してください！コミュニティはあなたが学割サービスを最大限活用できるようサポートします。
        
        質問する前に、以下をご確認ください：
        - 基本的な使用方法は [README.md](../README.md)
        - 詳細なドキュメントは [Wiki](../../wiki)
        - 類似の質問は [既存のディスカッション](../../discussions)

  - type: dropdown
    id: help-type
    attributes:
      label: 必要なヘルプの種類
      description: どのようなヘルプが必要ですか？
      options:
        - インストールのヘルプ
        - 使用方法の質問
        - 設定の問題
        - ブラウザの互換性
        - 機能が動作しない
        - その他
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: あなたの質問
      description: 何にヘルプが必要ですか？
      placeholder: 質問や問題を詳しく説明してください...
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: これまでに試したこと
      description: この問題を解決するために、これまでにどのような手順を試しましたか？
      placeholder: これまでに試したトラブルシューティング手順をリストアップしてください...

  - type: dropdown
    id: browser
    attributes:
      label: ブラウザ
      description: 使用しているブラウザを選択してください
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - その他

  - type: dropdown
    id: userscript-manager
    attributes:
      label: ユーザースクリプトマネージャー
      description: 使用しているユーザースクリプトマネージャーを選択してください
      options:
        - Tampermonkey
        - Greasemonkey
        - Violentmonkey
        - その他

  - type: textarea
    id: additional-info
    attributes:
      label: 追加情報
      description: サポートに役立つかもしれないその他の詳細
      placeholder: エラーメッセージ、スクリーンショット、特定のウェブサイトなど