title: "💡 アイデアと提案"
labels: [discussion, ideas]
body:
  - type: markdown
    attributes:
      value: |
        💡 **アイデアを共有してください！** 
        
        ここは学割サービスのための新機能、改善、またはクリエイティブなアイデアをブレインストーミングするのに最適な場所です。
        
        あなたの提案は、このプロジェクトをみんなにとってより良いものにするのに役立ちます！

  - type: textarea
    id: idea
    attributes:
      label: あなたのアイデア
      description: あなたのアイデアや提案は何ですか？
      placeholder: アイデアを詳しく説明してください...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解決する問題
      description: このアイデアはどのような問題を解決し、どのような改善をもたらしますか？
      placeholder: このアイデアがもたらす利益や解決する問題を説明してください...

  - type: textarea
    id: implementation
    attributes:
      label: 実装に関する考え
      description: これをどのように実装できるかについて、何か考えはありますか？
      placeholder: 技術的な検討事項、UIモックアップ、実装アイデアなど...

  - type: checkboxes
    id: involvement
    attributes:
      label: 関与
      description: このアイデアの実現に協力していただけますか？
      options:
        - label: 実装に協力したい
        - label: テストに協力したい
        - label: デザイン/UXに協力したい
        - label: アイデアを共有するだけで、他の人に検討してもらいたい

  - type: textarea
    id: examples
    attributes:
      label: 例や参考資料
      description: これまでに見たことのある例、参考資料、または類似の実装はありますか？
      placeholder: 類似機能のリンク、スクリーンショット、例など...